### ISSUE TITLE
Todo-list MVP

### ISSUE THREAD

**Issue by howtodoappdevelopment** [howtodoappdevelopment/blank-page#1]
### Shared
- [x] top bar
- [x] side navbar
- [x] buttons
- [x] typography
- [x] list item
  - [x] remove
  - [x] edit
  - [x] done
  - [ ] draggable
- [x] routing
- [ ] dexie storage or alternative
- [ ] forms

### Pages
- [ ] Todo list view
  - [x] wireframe
  - [x] mock
  - [x] user journey
  - [ ] focus mode
  - [ ] dark mode
  - [ ] add new
  - [ ] edit
- [ ] Inbox list view
  - [x] wireframe
  - [x] mock
  - [x] user journet
  - [ ] schedule
- [ ] Trash list view
  - [x] wireframe
  - [x] mock
  - [x] user journet
  - [ ] restore
  - [ ] auto-remove

## Phase II
- [ ] Planning view (WIP)
  - [ ] wireframe
  - [ ] mock
  - [ ] user journey

## Phase III
- [ ] PWA
- [ ] TWA
- [ ] desktop app
- [ ] browser extension

### Phase III
- [ ] landing page
- [ ] marketing materials
- [ ] auto deployment setup to web
- [ ] Android Marketplace deployment
- [ ] auto deployment to browser extension
