### ISSUE TITLE
Markdown input

### ISSUE THREAD

**Issue by howtodoappdevelopment** [howtodoappdevelopment/blank-page#2]
[Basic markdown](https://www.markdownguide.org/basic-syntax/)
[Extended markdown](https://www.markdownguide.org/extended-syntax/)

---

- [ ] Basic elements
  - [x] standard alpha-numeric
    - [x] paragraph
    - [x] span
  - [ ] bold/strong
- [ ] vertical line

```
\*\*double asterisks\*\*

\_\_double underscores\_\_
```

  - [x] headers
  - [ ] check box (done and not done)
  - [ ] code block
  - [ ] code snippet
  - [ ] italic

```
*single asterisks*

_single underscores_
```

  - [ ] blockquotes
  - [ ] list
    - [ ] ordered
    - [ ] unordered
  - [ ] math blocks (optional)
  - [ ] tables
  - [ ] footnotes (optional)
  - [ ] url
       automatically link standard URLs (www.google.com)
  - [ ] internal link: [this link](#block-elements)
  - [ ] reference url

```
[an example][id]
[id]: http://example.com/  "Optional Title Here"
```

```
\[Google][]
\[Google]: http://google.com/
```

  - [ ] iamges 

```
\!\[Alt text](/path/to/img.jpg)

\!\[Alt text](/path/to/img.jpg "Optional title")
```

  - [ ] strike trough (~~txt~~)
  - [ ] highlight (==high==)

- [ ] HTML
  - [ ] iframe
  - [ ] span + styles
  - [ ] video

- [ ] extensibility
  - [ ] themes (optional)
  - [ ] additional elements from external libraries

- [ ] Actions
  - [ ] tab
  - [ ] copy
  - [ ] cut
  - [ ] paste
  - [ ] find in text
  - [ ] new line

**Comment by howtodoappdevelopment** [comment]
Basic compositions
- [ ] replace elements with
- [ ] find elements by text
- [ ] add new content editable paragraph
- [ ] re-render paragraph
- [x] get cursor position (current element + position as letter nr)
- [x] set cursor position (number)
- [ ] handle
  - [ ] ctrl + b
  - [ ] ctrl + f
  - [ ] ctrl + i
  - [x] ctrl + c
  - [x] ctrl + x
  - [x] ctrl + v
        > ctrl + c, ctrl + v, ctrl + z can be easily handled by providing 2 types of view: **markdown**, **live**
  - [ ] enter
  - [ ] esc
  - [ ] ctrl + z
  - [ ] ctrl + y
  - [x] ctrl + 1, ... (headers)
  - [ ] ctrl + '+' (increase size)
  - [ ] ctrl + '-' (decrease size)
- [ ] add new line
- [ ] backspace on empty element (remove line)
- [ ] allowed text decorations in specific fields (not compatible code block + code snippet, ...)

**Comment by howtodoappdevelopment** [comment]
- [x] Nesting of elements 

```
- [ ] test
      > quote
```

**Comment by howtodoappdevelopment** [comment]
- [ ] recalculate ordered list numbers
- [ ] ordered list items and unordered list items children should have different icons

**Comment by howtodoappdevelopment** [comment]
- [ ] add beneath node
- [ ] remove node

**Comment by howtodoappdevelopment** [comment]
- [ ] all markdown elements configs should contain allowed text transformations by id
- [ ] all markdown text transformation elements should have ids

**Comment by howtodoappdevelopment** [comment]
- [ ] skip events on which re-render is run (like arrows)

**Comment by howtodoappdevelopment** [comment]
- [ ] on empty page fill with paragraphs

**Comment by howtodoappdevelopment** [comment]
- [ ] comment \<!-- --\>

**Comment by howtodoappdevelopment** [comment]
- [ ] add focus mode
- [ ] add writer mode
- [ ] add pure markdown mode
- [ ] add languages support for code block

**Comment by howtodoappdevelopment** [comment]
- [ ] smooth writing 
      https://www.codesdope.com/blog/article/12-creative-css-and-javascript-text-typing-animati/
      https://freefrontend.com/css-typing-text/
